pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'      // Nom du JDK configuré dans Jenkins
        maven 'M2_HOME'      // Nom de Maven configuré dans Jenkins
    }

    environment {
        SONAR_TOKEN     = credentials('sonar-token')
        DOCKERHUB_TOKEN = credentials('DOCKERHUB_TOKEN')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/amenallahbk/amenallahboukhris_devops.git',
                        credentialsId: 'git-credentials'
                    ]]
                ])
            }
        }

        stage('Clean') {
            steps {
                dir('TP-Projet-2025') {
                    sh 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('TP-Projet-2025') {
                    sh 'mvn compile'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('TP-Projet-2025') {
                    withSonarQubeEnv('sonarqube') {
                        sh """
                        mvn sonar:sonar \
                          -Dsonar.projectKey=amenallahboukhris_devops \
                          -Dsonar.host.url=http://192.168.33.10:9000 \
                          -Dsonar.login=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('TP-Projet-2025') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('TP-Projet-2025') {
                    sh '''
                    docker build -t amounboukhris/tpfoyer:1.0 .
                    echo $DOCKERHUB_TOKEN | docker login -u amounboukhris --password-stdin
                    docker push amounboukhris/tpfoyer:1.0
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f TP-Projet-2025/k8s/'
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'TP-Projet-2025/target/*.jar'
        }
        failure {
            echo '❌ Pipeline échoué'
        }
    }
}
